#spring application configuration
spring:
  application:
    name: ticket_resell_be
  #database configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ticket_resell
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#server configuration
server:
  port: 8081
  servlet:
    context-path: /
#payment configuration
payos:
  client-id: ${YOUR_CLIENT_ID}
  api-key: ${YOUR_API_KEY}
  checksum-key: ${YOUR_CHECKSUM_KEY}